version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../recruiter-management-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend