"""add created_at and updated_at to jobs

Revision ID: 53ff95aef4f9
Revises: 2d9972cfeb9c
Create Date: 2026-06-05 15:06:25.725589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ff95aef4f9'
down_revision: Union[str, Sequence[str], None] = '2d9972cfeb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
