"""add created_at and updated_at to candidate

Revision ID: ef30f2374c13
Revises: 53ff95aef4f9
Create Date: 2026-06-05 18:43:19.188274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef30f2374c13'
down_revision: Union[str, Sequence[str], None] = '53ff95aef4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('candidates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'updated_at')
    op.drop_column('candidates', 'created_at')
    # ### end Alembic commands ###
